/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Equipo
 */
public class fbienvenida extends javax.swing.JPanel {

    /**
     * Creates new form fbienvenida
     */
    public fbienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1120, 677));
        setMinimumSize(new java.awt.Dimension(1120, 677));
        setPreferredSize(new java.awt.Dimension(1120, 677));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(126, 113, 255));
        jLabel1.setText("Nuestra clinica");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 259, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>\n\t<p>Vet Martin es una clínica veterinaria comprometida con el bienestar y la salud de tus mascotas. Con un equipo de profesionales apasionados y altamente capacitados, ofrecemos una amplia gama de servicios médicos, desde consultas generales hasta cirugías especializadas. </p>\n\t<p>En Vet Martin, nos esforzamos por brindar atención personalizada y de calidad a cada uno de nuestros pacientes peludos. Nuestra misión es mantener a tus mascotas felices y saludables en todas las etapas de sus vidas.</p>\n</html>");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 76, 848, 137));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setText("<html>\n\t<p>Nuestras instalaciones en Vet Martin están diseñadas pensando en el confort y bienestar tanto de las \t\tmascotas como de sus dueños. Contamos con modernas salas de consulta equipadas con la última tecnología médica, donde nuestros veterinarios expertos realizan exámenes exhaustivos y brindan diagnósticos precisos.</p>\n\n<p>Además, disponemos de áreas de espera cómodas y acogedoras, donde tanto las mascotas como sus dueños pueden relajarse antes de su consulta. Nuestra clínica también cuenta con quirófanos completamente equipados para realizar cirugías seguras y efectivas, así como laboratorios de última generación para análisis clínicos rápidos y precisos.</p>\n</html>");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 556, 195));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(126, 113, 255));
        jLabel4.setText("¿Que es Vet Martín?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 27, 259, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clinica.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 280, 210));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perrete.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 230, 180));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setText("@vetmartin");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 110, 20));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setText("@vetmartin");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 110, 20));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setText("@vetmartin");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 110, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook_logo_icon_147291 (1).png"))); // NOI18N
        jLabel10.setRequestFocusEnabled(false);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Instagram-Icon (1).png"))); // NOI18N
        jLabel11.setRequestFocusEnabled(false);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/twitter (1).png"))); // NOI18N
        jLabel12.setRequestFocusEnabled(false);
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
