/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Equipo
 */
public class fclientes extends javax.swing.JPanel {

    /**
     * Creates new form fclientes
     */
    public fclientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        actualizarcli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailcli = new javax.swing.JTextField();
        idclientecli = new javax.swing.JTextField();
        nombrecli = new javax.swing.JTextField();
        apellidocli = new javax.swing.JTextField();
        telefonocli = new javax.swing.JTextField();
        direccioncli = new javax.swing.JTextField();
        eliminarcli = new javax.swing.JButton();
        insertarcli = new javax.swing.JButton();
        modificarcli = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1120, 677));
        setPreferredSize(new java.awt.Dimension(1120, 677));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_cliente", "nombre", "apellido", "telefono", "direccion", "email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaclientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, 1072, 221));

        actualizarcli.setBackground(new java.awt.Color(160, 30, 250));
        actualizarcli.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        actualizarcli.setForeground(new java.awt.Color(255, 255, 255));
        actualizarcli.setText("Actualizar");
        actualizarcli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(actualizarcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 98, 39));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 98, 35));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("Id Cliente:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 98, 49));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("Apellido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 98, 35));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("Telefono");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 98, 35));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setText("Direccion");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 98, 35));
        add(emailcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 230, 40));
        add(idclientecli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 230, 40));
        add(nombrecli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 230, 40));
        add(apellidocli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 230, 40));
        add(telefonocli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 230, 40));
        add(direccioncli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 230, 40));

        eliminarcli.setBackground(new java.awt.Color(160, 30, 250));
        eliminarcli.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        eliminarcli.setForeground(new java.awt.Color(255, 255, 255));
        eliminarcli.setText("Insertar");
        eliminarcli.setMaximumSize(new java.awt.Dimension(90, 29));
        eliminarcli.setMinimumSize(new java.awt.Dimension(90, 29));
        eliminarcli.setPreferredSize(new java.awt.Dimension(90, 29));
        add(eliminarcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, -1, -1));

        insertarcli.setBackground(new java.awt.Color(160, 30, 250));
        insertarcli.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        insertarcli.setForeground(new java.awt.Color(255, 255, 255));
        insertarcli.setText("Insertar");
        insertarcli.setMaximumSize(new java.awt.Dimension(90, 29));
        insertarcli.setMinimumSize(new java.awt.Dimension(90, 29));
        insertarcli.setPreferredSize(new java.awt.Dimension(90, 29));
        add(insertarcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        modificarcli.setBackground(new java.awt.Color(160, 30, 250));
        modificarcli.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        modificarcli.setForeground(new java.awt.Color(255, 255, 255));
        modificarcli.setText("Modificar");
        modificarcli.setMaximumSize(new java.awt.Dimension(90, 29));
        modificarcli.setMinimumSize(new java.awt.Dimension(90, 29));
        modificarcli.setPreferredSize(new java.awt.Dimension(90, 29));
        add(modificarcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarcli;
    private javax.swing.JTextField apellidocli;
    private javax.swing.JTextField direccioncli;
    private javax.swing.JButton eliminarcli;
    private javax.swing.JTextField emailcli;
    private javax.swing.JTextField idclientecli;
    private javax.swing.JButton insertarcli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarcli;
    private javax.swing.JTextField nombrecli;
    private javax.swing.JTable tablaclientes;
    private javax.swing.JTextField telefonocli;
    // End of variables declaration//GEN-END:variables
}
