/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.EmailUtil;
import java.security.SecureRandom;
import java.util.Properties;
import modelo.ConexionBD;

/**
 *
 * @author Hugo Martín Morales DAM2B
 */
public class Reccontra extends javax.swing.JFrame {

    /**
     * Creates new form Reccontra
     */
    public Reccontra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mancorreo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperar contraseña");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nombrejpg.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, -1, -1));

        mancorreo.setBackground(new java.awt.Color(160, 30, 250));
        mancorreo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mancorreo.setForeground(new java.awt.Color(255, 255, 255));
        mancorreo.setText("Correo");
        mancorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mancorreoActionPerformed(evt);
            }
        });
        jPanel1.add(mancorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 480, 120, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Correo (Rec.Contra)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 180, 30));

        correo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(160, 30, 250));
        correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correoMousePressed(evt);
            }
        });
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 300, 40));

        login.setBackground(new java.awt.Color(160, 30, 250));
        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 700, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mancorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mancorreoActionPerformed
        //ESTA ES LA LOGICA DEL CORREO, PERO COMO NO ME VA HIBERNATE NO SE SI FUNCIONA...
        /*final String fromEmail = "hugomartinmorales729@gmail.com";
        final String password = "losqrgkgsmxgfgqf";
        final String toEmail = "hugo.marmor@educa.jcyl.es";

    try {
        //para generar nueva contraseña
        String nuevaContraseña = generarNuevaContraseña();

        //actualizar la contraseña en la base de datos
        actualizarContraseñaEnBaseDeDatos(toEmail, nuevaContraseña);

        //enviar el correo electrónico con la nueva contraseña
        sendEmailWithNewPassword(toEmail, nuevaContraseña, fromEmail, password);

        //mensaje de éxito o redirección a una nueva ventana
        System.out.println("Se ha enviado una nueva contraseña por correo electrónico.");

    } catch (Exception e) {
        e.printStackTrace();
        System.out.println("Error");
    }
}   

    private String generarNuevaContraseña() {
         int longitudContraseña = 12;

        //caracteres permitidos para la contraseña
        String caracteresPermitidos = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

        //aleatorio
        SecureRandom random = new SecureRandom();

        //crear la nueva contraseña
        StringBuilder nuevaContraseña = new StringBuilder();
        for (int i = 0; i < longitudContraseña; i++) {
            int indice = random.nextInt(caracteresPermitidos.length());
            nuevaContraseña.append(caracteresPermitidos.charAt(indice));
        }

        //delvover la contra
        return nuevaContraseña.toString();
    }

    private void actualizarContraseñaEnBaseDeDatos(String email, String nuevaContraseña) {
        //lógica para actualizar la contraseña en la base de datos
        //falta el metodo verificarCredenciales en la clase ConexionBD
        ConexionBD.actualizarContraseña(email, nuevaContraseña);
    }

    private void sendEmailWithNewPassword(String toEmail, String nuevaContraseña, String fromEmail, String password) {
        Properties props = new Properties();
        //configuración del servidor de correo electrónico

        Session session = Session.getDefaultInstance(props, new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, password);
            }
        });

        String subject = "Recuperación de Contraseña";
        String body = "Tu nueva contraseña es: " + nuevaContraseña;

        //envío del correo electrónico
        EmailUtil.sendEmail(session, toEmail, subject, body, fromEmail, password);*/
    }//GEN-LAST:event_mancorreoActionPerformed

    private void correoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoMousePressed
        // TODO add your handling code here:
        if(correo.getText().equals("email@dominio.es")){
            correo.setText("");
        }
    }//GEN-LAST:event_correoMousePressed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        //cambiar al login
        dispose();
        Login loginFrame = new Login();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reccontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reccontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reccontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reccontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reccontra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JButton mancorreo;
    // End of variables declaration//GEN-END:variables
}
